### ISSUE TITLE
Include other runner on coop runs

### ISSUE THREAD

**Issue by BumpyAHK** [JaioCG/p2-autorenderle#13]
No idea if the api even allows for this. Would be neat to see.

**Comment by JaioCG** [comment]
Yes and no. Technically autosubmit puts the other runner's username as the run comment, which I can read, but if a run was submitted manually, or done before autosubmit, then the comment could be different or just have no comment at all.

**Comment by JaioCG** [comment]
I'll keep this up for now if I have an idea on how to implement this well but don't think there's a good way to filter only runs that have a username-only comment.
