### ISSUE TITLE
autorenderle getting wrong rank when rank is tied

### ISSUE THREAD

**Issue by FifthWit** [JaioCG/p2-autorenderle#14]
on maps like neuro sabo where most ranks are tied, the autorenderle takes the rank as whatever the position it is on the boards, heres a example of what happened to me, I was doing guess the rank when I saw a 1:00.50 and I guessed rank 26, it said it was 33rd, if you look at the rank its 26th, but the position of the runs(how many spots it goes down) is the 33rd spot. idk much about the autorender api, but from what I've read on the documentation the autorender can send you the cur rank

**Comment by JaioCG** [comment]
The way the boards measure ranks for tied is how you said where it would be the 33rd spot on the boards, the tied number is just a visual thing. If you look into the json for the time on the boards api you can see the actual ranking is 33rd.

It would be nice to get this fixed but I don't think that's something that can be done without significant rewrites to boards.
